import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/personal/navigation";
import Banner from "@/components/personal/banner";
import ProductCard from "@/components/personal/products/product-card";
import CategoryCard from "@/components/personal/products/category-card";
import AboutUsSection from "@/components/personal/utils/aboutUsSection";
import { BlurEffectCard, BlurEffectContainer } from "@/components/ui/blur-effer";
import DescriptionCarousel from "@/components/personal/description-carousel";
import NewsletterSection from "@/components/personal/utils/newsletterSection";
import ArticlesSection from "@/components/personal/utils/articles";
import FAQSection from "@/components/personal/utils/faqSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const publicSans = Public_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-public-sans',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${publicSans.variable} antialiased `}
      >
        <Navbar />
        <Banner />
        {/* <BlurEffectContainer className="grid grid-cols-2 gap-10 max-w-screen-base mx-auto px-16">
          <BlurEffectCard>
          <CategoryCard
              title="Audio"
              description="Lorem ipsum dolor sit amet, consectetur adipiscing elit elementum nisl facilisis."
              imageUrl="/assets/categories/audio.png"
              linkText="Explore category"
              linkHref="/categories/audio"
            />
          </BlurEffectCard>

          <BlurEffectCard>
          <CategoryCard
              title="Audio"
              description="Lorem ipsum dolor sit amet, consectetur adipiscing elit elementum nisl facilisis."
              imageUrl="/assets/categories/audio.png"
              linkText="Explore category"
              linkHref="/categories/audio"
            />
          </BlurEffectCard>
          <BlurEffectCard>
          <CategoryCard
              title="Audio"
              description="Lorem ipsum dolor sit amet, consectetur adipiscing elit elementum nisl facilisis."
              imageUrl="/assets/categories/audio.png"
              linkText="Explore category"
              linkHref="/categories/audio"
            />
          </BlurEffectCard>
          <BlurEffectCard>
          <CategoryCard
              title="Audio"
              description="Lorem ipsum dolor sit amet, consectetur adipiscing elit elementum nisl facilisis."
              imageUrl="/assets/categories/audio.png"
              linkText="Explore category"
              linkHref="/categories/audio"
            />
          </BlurEffectCard>
          <BlurEffectCard>
          <CategoryCard
              title="Audio"
              description="Lorem ipsum dolor sit amet, consectetur adipiscing elit elementum nisl facilisis."
              imageUrl="/assets/categories/audio.png"
              linkText="Explore category"
              linkHref="/categories/audio"
            />
          </BlurEffectCard>
        </BlurEffectContainer>
        <AboutUsSection />
        <div className="max-w-screen-base mx-auto">
          <DescriptionCarousel />
        </div>

        <div className="max-w-screen-base mx-auto">
          <NewsletterSection/>
        </div>

        <div className="max-w-screen-base mx-auto">
          <ArticlesSection/>
        </div>

        <div className="max-w-screen-base mx-auto">
          <FAQSection/>
        </div> */}
        {children}
      </body>
    </html>
  );
}
